# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91e6662dac10ba421ee1e8c0b0fc227895918553cf9cab200c9c8ebb4f8517a12b21b76e20e4073d162629b6a584e11c1f453b2d6f8dbe01ad66db23f26ad081

test:
  secret_key_base: 41d91275920e3af13e9feda396b8d64e2c126eb02a6a60d90a74c7e8abf575b8326cdc2283a4c10644435c12c800edf76c765faf28cdaa32620ca741fad5bebd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
